[package]
name = "nanocoin-rs"
version = "0.1.0"
edition = "2021"
description = ""
documentation = "https://docs.rs/nanocoin-rs"
readme = "README.md"
repository = "https://github.com/shtsoft/nanocoin-rs"
license = "GPL-3.0-or-later"
keywords = []
categories = []

[dependencies]
